### ISSUE TITLE
Error in org.redisson.example.services.ExecutorServiceExamples

### ISSUE THREAD

**Issue by zhou-kevin** [redisson/redisson-examples#12]
When I try ExecutorServiceExamples, I get following error message :
==============
java.lang.IllegalArgumentException: java.io.IOException: java.lang.RuntimeException: Class org.redisson.example.services.ExecutorServiceExamples$RunnableTask does not implement Serializable or externalizable
        at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:375)
        at org.redisson.RedissonExecutorService.execute(RedissonExecutorService.java:325)
        at org.redisson.example.services.ExecutorServiceExamples.main(ExecutorServiceExamples.java:73)
      (and more)

I'm using JDK 1.8.0_121, and use the Redis cluster in another machine.

Can someone tell me the requirements to make this example pass ? Thanks.

**Comment by mrniko** [comment]
Fixed, thanks for report!
