### ISSUE TITLE
Can not catch InterruptedException

### ISSUE THREAD

**Issue by irlyy** [redisson/redisson-examples#14]
public static void main(String[] args) throws InterruptedException {
        // connects to 127.0.0.1:6379 by default
        Config config = new Config();
        config.useSingleServer().setAddress("redis://192.168.99.100:6379");
        RedissonClient redisson = Redisson.create(config);

        RBlockingQueue<String> queue = redisson.getBlockingQueue("myQueue");

        Thread t = new Thread(() -> {
            try {
//                String element = queue.take(10, TimeUnit.SECONDS);
                String secondElement = queue.take();
            } catch (InterruptedException e) {
                System.out.println("InterruptedException");
                e.printStackTrace();
            }
        });
        t.start();
        TimeUnit.SECONDS.sleep(3);
        t.interrupt();

        TimeUnit.SECONDS.sleep(3);
        redisson.shutdown();
    }

The output is as below:
Exception in thread "Thread-1" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:400)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:204)
	at org.redisson.RedissonObject.get(RedissonObject.java:94)
	at org.redisson.RedissonBlockingQueue.take(RedissonBlockingQueue.java:80)
	at org.redisson.example.collections.BlockingQueueInterruptedExamples.lambda$main$0(BlockingQueueInterruptedExamples.java:42)
	at java.lang.Thread.run(Thread.java:748)

**Comment by irlyy** [comment]
Seems do not catch InterruptedException.

**Comment by mrniko** [comment]
It's a bug. Will fix it in this issue https://github.com/redisson/redisson/issues/2327.
